name: README Auto-Update

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Update Last Update Timestamp
        run: |
          DATE=$(date +"%Y-%m-%d %H:%M:%S %Z")
          sed -i "s|{{last_update}}|$DATE|g" README.md

      - name: Commit and Push Changes
        run: |
          git config --global user.name "dogsme"
          git config
