name: README

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: README
        run: |
          DATE=$(date +"%Y-%m-%d %H:%M:%S %Z")
          sed -i "s|{{last_update}}|$DATE|g" README.md

      - name: Commit changes
        run: |
          git config --global user.name "dogsme"
          git config --global user.email "your-email@example.com"
          git add README.md
          git commit -m "chore: update README [skip ci]" || echo "No changes"
          git push
